/**
 * SAMPLE DIRECTORY — Chennai / Tamil Nadu.
 *
 * ============================================================================
 *  READ THIS BEFORE LAUNCHING PUBLICLY
 * ============================================================================
 *  These are ILLUSTRATIVE placeholder entries assembled for a demo. Phone
 *  numbers here are NOT scraped from a live registry and several are patterned
 *  placeholders. Real contact details for every organisation MUST be manually
 *  confirmed by calling the number and checking it still serves the stated
 *  purpose, before this directory is shown to people in a real emergency.
 *
 *  Every row is written with `isSampleData: true`, which makes the UI show a
 *  "sample data" banner. A live launch means: verify each row, set
 *  `verified: true` with a real `lastVerifiedDate`, then flip
 *  DIRECTORY_IS_SAMPLE_DATA / app_config.isSampleData to "false".
 * ============================================================================
 *
 * Coordinates are real neighbourhood/city centroids (Chennai ~13.0827 N,
 * 80.2707 E) so distances and map pins behave sensibly, but the org entries
 * themselves are fictional stand-ins for the real local ecosystem.
 */

export const SAMPLE_ORGANIZATIONS = [
  {
    name: 'Blue Cross Animal Helpline (sample entry)',
    category: 'ngo',
    phone: '+91 98400 00001',
    altPhone: null,
    whatsapp: '919840000001',
    email: 'helpdesk@example.org',
    website: 'https://example.org/bluecross-sample',
    address: '48, NSC Bose Road, Kilpauk, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0395,
    lng: 80.1993,
    servicesOffered: ['rescue', 'first_aid', 'adoption', 'sterilization', 'shelter'],
    animalTypesHandled: ['dog', 'cat', 'other'],
    is24x7: true,
    operatingHours: '24x7 helpline',
    verified: false,
    notes: 'SAMPLE. Volunteer-run helpline; typical response for trapped/injured strays.',
  },
  {
    name: 'Coastal Animal Rescue Trust (sample entry)',
    category: 'ngo',
    phone: '+91 98400 00002',
    altPhone: '+91 44 2820 0002',
    whatsapp: '919840000002',
    email: null,
    website: null,
    address: '12, Besant Nagar Beach Road, Besant Nagar, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0067,
    lng: 80.2668,
    servicesOffered: ['rescue', 'first_aid', 'rehab', 'adoption'],
    animalTypesHandled: ['dog', 'cat', 'bird'],
    is24x7: false,
    operatingHours: '8:00 AM - 8:00 PM',
    verified: false,
    notes: 'SAMPLE. Focused on beach-side stranded dogs and seabird releases.',
  },
  {
    name: 'Tamil Nadu Animal Speak Foundation (sample entry)',
    category: 'ngo',
    phone: '+91 98400 00003',
    altPhone: null,
    whatsapp: '919840000003',
    email: 'rescue@example.org',
    website: 'https://example.org/tnasf-sample',
    address: '7, Ram Nagar, Coimbatore',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    lat: 11.0168,
    lng: 76.9558,
    servicesOffered: ['rescue', 'sterilization', 'adoption', 'shelter'],
    animalTypesHandled: ['dog', 'cat', 'cattle', 'goat'],
    is24x7: false,
    operatingHours: '9:00 AM - 6:00 PM',
    verified: false,
    notes: 'SAMPLE. Regional NGO covering Coimbatore; does not operate an ambulance.',
  },
  {
    name: 'Kaveri Stray Animal Care (sample entry)',
    category: 'ngo',
    phone: '+91 98400 00004',
    altPhone: null,
    whatsapp: '919840000004',
    email: null,
    website: null,
    address: '22, Trichy Main Road, Madurai',
    city: 'Madurai',
    state: 'Tamil Nadu',
    lat: 9.9252,
    lng: 78.1198,
    servicesOffered: ['rescue', 'first_aid', 'adoption'],
    animalTypesHandled: ['dog', 'cat', 'cattle'],
    is24x7: false,
    operatingHours: '9:00 AM - 7:00 PM',
    verified: false,
    notes: 'SAMPLE. Madurai-area rescue group.',
  },
  {
    name: 'Chennai Veterinary Hospital — Animal Emergency Wing (sample entry)',
    category: 'veterinary',
    phone: '+91 44 2820 0010',
    altPhone: '+91 98400 00010',
    whatsapp: '919840000010',
    email: 'emergency@example.org',
    website: 'https://example.org/cvh-sample',
    address: '4, Pantheon Road, Egmore, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0732,
    lng: 80.2619,
    servicesOffered: ['first_aid', 'ambulance', 'rescue', 'cremation'],
    animalTypesHandled: ['dog', 'cat', 'cattle', 'bird', 'other'],
    is24x7: true,
    operatingHours: '24x7 emergency, OPD 9:00 AM - 8:00 PM',
    verified: false,
    notes: 'SAMPLE. Best first call for bleeding, hit-and-run and poisoning cases.',
  },
  {
    name: 'Anna Nagar Multi-Speciality Veterinary Centre (sample entry)',
    category: 'veterinary',
    phone: '+91 44 2620 0011',
    altPhone: null,
    whatsapp: '919840000011',
    email: null,
    website: null,
    address: 'AB-24, Anna Nagar Main Road, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0850,
    lng: 80.2101,
    servicesOffered: ['first_aid', 'ambulance', 'sterilization'],
    animalTypesHandled: ['dog', 'cat', 'bird', 'other'],
    is24x7: false,
    operatingHours: '8:00 AM - 9:00 PM',
    verified: false,
    notes: 'SAMPLE. No night emergency cover; call before travelling after 9 PM.',
  },
  {
    name: 'T. Nagar Veterinary Care Centre (sample entry)',
    category: 'veterinary',
    phone: '+91 44 2833 0012',
    altPhone: null,
    whatsapp: '919840000012',
    email: null,
    website: null,
    address: '31, Ranganathan Street, T. Nagar, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0418,
    lng: 80.2341,
    servicesOffered: ['first_aid', 'sterilization', 'rehab'],
    animalTypesHandled: ['dog', 'cat', 'bird', 'reptile'],
    is24x7: false,
    operatingHours: '10:00 AM - 8:00 PM',
    verified: false,
    notes: 'SAMPLE. Handles bird and reptile injuries.',
  },
  {
    name: 'Velachery Animal Hospital (sample entry)',
    category: 'veterinary',
    phone: '+91 44 2245 0013',
    altPhone: null,
    whatsapp: '919840000013',
    email: null,
    website: null,
    address: '105, Bazaar Road, Velachery, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 12.9750,
    lng: 80.2210,
    servicesOffered: ['first_aid', 'ambulance'],
    animalTypesHandled: ['dog', 'cat', 'other'],
    is24x7: true,
    operatingHours: '24x7',
    verified: false,
    notes: 'SAMPLE. South Chennai 24x7 option.',
  },
  {
    name: 'Greater Chennai Corporation — Animal Control Unit (sample entry)',
    category: 'municipal',
    phone: '+91 44 2827 0000',
    altPhone: '+91 94440 00000',
    whatsapp: null,
    email: null,
    website: null,
    address: 'Ripon Building, Anna Salai, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0785,
    lng: 80.2707,
    servicesOffered: ['capture_only', 'cremation'],
    animalTypesHandled: ['dog', 'cattle', 'other'],
    is24x7: false,
    operatingHours: '10:00 AM - 6:00 PM (ward office)',
    verified: false,
    notes: 'SAMPLE. Stray capture and roadkill removal only — NOT equipped for medical treatment.',
  },
  {
    name: 'Chennai City Animal Control — South Zone (sample entry)',
    category: 'municipal',
    phone: '+91 44 2827 0020',
    altPhone: null,
    whatsapp: null,
    email: null,
    website: null,
    address: 'Zone Office, Guindy, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0067,
    lng: 80.2206,
    servicesOffered: ['capture_only', 'cremation'],
    animalTypesHandled: ['dog', 'cattle', 'other'],
    is24x7: false,
    operatingHours: '9:00 AM - 5:30 PM',
    verified: false,
    notes: 'SAMPLE. Use for aggressive strays and roadkill removal in the south zone.',
  },
  {
    name: 'Madurai Municipal Corporation — Animal Control (sample entry)',
    category: 'municipal',
    phone: '+91 45 2820 0021',
    altPhone: null,
    whatsapp: null,
    email: null,
    website: null,
    address: 'Town Hall Road, Madurai',
    city: 'Madurai',
    state: 'Tamil Nadu',
    lat: 9.9195,
    lng: 78.1190,
    servicesOffered: ['capture_only', 'cremation'],
    animalTypesHandled: ['dog', 'cattle', 'other'],
    is24x7: false,
    operatingHours: '9:00 AM - 5:00 PM',
    verified: false,
    notes: 'SAMPLE. Capture only.',
  },
  {
    name: 'Coimbatore Corporation — Stray Cell (sample entry)',
    category: 'municipal',
    phone: '+91 422 230 0022',
    altPhone: null,
    whatsapp: null,
    email: null,
    website: null,
    address: 'Bharathiar Road, Coimbatore',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    lat: 11.0168,
    lng: 77.0,
    servicesOffered: ['capture_only'],
    animalTypesHandled: ['dog', 'cattle', 'other'],
    is24x7: false,
    operatingHours: '9:00 AM - 5:00 PM',
    verified: false,
    notes: 'SAMPLE. Capture only, no medical care.',
  },
  {
    name: 'Wildlife SOS-style Large Animal Rescue Unit (sample entry)',
    category: 'ngo',
    phone: '+91 98400 00005',
    altPhone: null,
    whatsapp: '919840000005',
    email: null,
    website: null,
    address: 'Forest Survey Camp, Ooty',
    city: 'Ooty',
    state: 'Tamil Nadu',
    lat: 11.4102,
    lng: 76.6950,
    servicesOffered: ['rescue', 'rehab', 'ambulance'],
    animalTypesHandled: ['wildlife', 'monkey', 'other'],
    is24x7: true,
    operatingHours: '24x7',
    verified: false,
    notes: 'SAMPLE. For big cats, elephants and monkey rescue — not for street dogs.',
  },
  {
    name: 'Bull & Cow Rescue Collective (sample entry)',
    category: 'ngo',
    phone: '+91 98400 00006',
    altPhone: null,
    whatsapp: '919840000006',
    email: null,
    website: null,
    address: 'Kanchipuram outskirts, Chennai',
    city: 'Kanchipuram',
    state: 'Tamil Nadu',
    lat: 12.8342,
    lng: 79.7036,
    servicesOffered: ['rescue', 'shelter', 'first_aid'],
    animalTypesHandled: ['cattle', 'goat'],
    is24x7: false,
    operatingHours: '6:00 AM - 8:00 PM',
    verified: false,
    notes: 'SAMPLE. Cattle that are injured or blocking roads on temple streets.',
  },
  {
    name: 'Injured Bird Rescue Centre (sample entry)',
    category: 'ngo',
    phone: '+91 98400 00007',
    altPhone: null,
    whatsapp: '919840000007',
    email: null,
    website: null,
    address: '15, Marine Drive, Besant Nagar, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0031,
    lng: 80.2710,
    servicesOffered: ['rescue', 'rehab', 'first_aid'],
    animalTypesHandled: ['bird'],
    is24x7: false,
    operatingHours: '7:00 AM - 7:00 PM',
    verified: false,
    notes: 'SAMPLE. Crows, kites, parrots and shorebirds hit by window panes or wires.',
  },
  {
    name: 'Chennai Street Cat Sterilisation Programme (sample entry)',
    category: 'ngo',
    phone: '+91 98400 00008',
    altPhone: null,
    whatsapp: '919840000008',
    email: null,
    website: null,
    address: 'Perungalathur, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 12.9184,
    lng: 80.2360,
    servicesOffered: ['sterilization', 'first_aid', 'adoption'],
    animalTypesHandled: ['cat'],
    is24x7: false,
    operatingHours: '9:00 AM - 5:00 PM',
    verified: false,
    notes: 'SAMPLE. TNR and vaccination; not an ambulance service.',
  },
];
